# Generated by Django 4.1.2 on 2022-10-27 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profanity_filter', models.BooleanField(default=True)),
                ('voted_bandnames', models.JSONField()),
                ('cumulative_score', models.IntegerField(default=0)),
                ('righteousness_level', models.CharField(default='Groupie', max_length=128)),
                ('last_ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
