# Generated by Django 4.1.2 on 2022-10-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_logged_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
