# Generated by Django 4.1 on 2022-09-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cumulative_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='righteousness_level',
            field=models.CharField(default='Groupie', max_length=128),
        ),
    ]
