# Generated by Django 4.1 on 2022-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_bandname_users_voted'),
        ('accounts', '0003_remove_profile_voted_bandnames_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voted_bandnames_list',
            field=models.ManyToManyField(to='main.bandname'),
        ),
    ]
