# Generated by Django 4.1.2 on 2023-06-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_voted_bandnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='voted_bandnames',
            field=models.JSONField(default=dict),
        ),
    ]
