# Generated by Django 4.1 on 2022-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bandname_date_submitted'),
        ('accounts', '0005_remove_profile_voted_bandnames_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voted_bandnames_2',
            field=models.ManyToManyField(to='main.bandname'),
        ),
    ]
