# Generated by Django 4.1 on 2022-10-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_voted_bandnames_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='voted_bandnames_2',
            new_name='voted_bandnames_list',
        ),
    ]
