# Generated by Django 4.1 on 2022-10-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_voted_bandnames_2_profile_voted_bandnames_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='voted_bandnames_list',
        ),
    ]
