# Generated by Django 4.1 on 2022-10-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_voted_bandnames_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
