# Generated by Django 4.1 on 2022-09-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnSubmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandname',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
