# Generated by Django 4.1 on 2022-09-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnSubmission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandname',
            old_name='downvotes',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='bandname',
            name='upvotes',
        ),
    ]
