# Generated by Django 4.1 on 2022-09-20 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnSubmission', '0002_alter_bandname_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandname',
            name='date_submitted',
            field=models.DateField(default=datetime.date(2022, 9, 20)),
        ),
    ]
