# Generated by Django 4.1 on 2022-09-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnSubmission', '0007_alter_bandname_date_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandname',
            name='date_submitted',
        ),
    ]
