# Generated by Django 4.1 on 2022-10-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandname',
            fields=[
                ('bandname', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('score', models.IntegerField()),
                ('date_submitted', models.DateField(default='2022-10-05')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
            ],
        ),
    ]
