# Generated by Django 4.1.2 on 2022-10-27 18:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandname',
            fields=[
                ('bandname', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('bandname_censored', models.CharField(default='', max_length=128)),
                ('username', models.CharField(max_length=150)),
                ('score', models.IntegerField()),
                ('date_submitted', models.DateField(default='2022-10-27')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('ip_addresses_voted', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(default='0.0.0.0'), default=['0.0.0.0'], size=None)),
            ],
        ),
    ]
