# Generated by Django 4.1.2 on 2023-06-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandname',
            name='date_submitted',
            field=models.DateField(default='2023-06-12'),
        ),
    ]
