# Generated by Django 4.1.2 on 2024-01-17 14:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandname',
            name='genres',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
