# Generated by Django 4.1.2 on 2022-10-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bandname_ip_addresses_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandname',
            name='bandname_censored',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='date_submitted',
            field=models.DateField(default='2022-10-25'),
        ),
    ]
