# Generated by Django 4.1 on 2022-09-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bandname_users_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandname',
            name='users_voted',
        ),
    ]
