# Generated by Django 4.1.2 on 2024-01-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_voted_bandnames'),
        ('main', '0003_genrevote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genrevote',
            unique_together={('user', 'bandname')},
        ),
    ]
