# Generated by Django 4.1.2 on 2024-01-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_voted_bandnames'),
        ('main', '0004_alter_genrevote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genrevote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='genrevote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genrevote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='genrevote',
            unique_together={('user', 'bandname', 'ip_address')},
        ),
    ]
