# Generated by Django 4.1 on 2022-10-01 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_bandname_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandname',
            name='users_voted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
