# Generated by Django 4.1 on 2022-10-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bandname_users_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandname',
            name='users_voted',
        ),
    ]
