# Generated by Django 4.1.2 on 2024-01-25 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_genrevote_unique_together_genrevote_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandname',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='ip_addresses_voted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), default=list, size=None),
        ),
    ]
