# Generated by Django 4.1.2 on 2024-01-25 18:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bandname_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandname',
            name='ip_addresses_voted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(blank=True, null=True), default=list, size=None),
        ),
    ]
