# Generated by Django 4.1 on 2022-10-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_bandname_users_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandname',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='bandname',
            name='date_submitted',
            field=models.DateField(default='2022-10-02'),
        ),
    ]
