# Generated by Django 4.1.2 on 2023-12-02 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bandname_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandname',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
